version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key
      - DJANGO_SETTINGS_MODULE=snippets.settings
    depends_on:
      - db

  test:
    build:
      context: .
    volumes:
      - .:/app
    command: >
      sh -c "pytest -v --maxfail=5 --disable-warnings"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=snippets.settings
      - SECRET_KEY=your-secret-key
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: